const nombres = [
  "Santiago",
  "Mateo",
  "Sebastián",
  "Alejandro",
  "Matías",
  "Diego",
  "Samuel",
  "Nicolás",
  "Daniel",
  "Martín",
  "Benjamín",
  "Leonardo",
  "Joaquín",
  "Lucas",
  "Gabriel",
  "Adrián",
  "Bruno",
  "Tomás",
  "Damián",
  "Leo",
  "Francisco",
  "Alonso",
  "Álvaro",
  "Miguel",
  "Ángel",
  "Valentino",
  "Rafael",
  "Andrés",
  "Franco",
  "Fernando",
  "León",
  "Emilio",
  "Marcos",
  "Julián",
  "Juan",
  "José",
  "Pedro",
  "Alexander",
  "Lorenzo",
  "David",
  "Mario",
  "Sergio",
  "Cristian",
  "Felipe",
  "Esteban",
  "Maximiliano",
  "Elías",
  "Erick",
  "Antonio",
  "Hugo",
  "Pablo",
  "Jorge",
  "Rodrigo",
  "ignacio",
  "Simón",
  "Carlos",
  "Javier",
  "Isaac",
  "Manuel",
  "Gonzalo",
  "Kevin",
  "Emmanuel",
  "Alan",
  "Eduardo",
  "Iván",
  "Vicente",
  "Cristóbal",
  "Néstor",
  "Arturo",
  "Wilmer",
  "Fabián",
  "Johan",
  "Fabio",
  "Luis",
  "Julio",
  "Oscar",
  "Héctor",
  "Leandro",
  "Aldo",
  "Víctor",
  "Omar",
  "Mauro",
  "Mauricio",
  "César",
  "Federico",
  "Jaime",
  "Danilo",
  "Armando",
  "James",
  "Jeisson",
  "Rubén",
  "Michael",
  "Enrique",
  "Xavier",
  "Fausto",
  "Renato",
  "Raúl",
  "Edilberto",
  "Ramón",
  "Patricio",
  "Félix",
  "Hernando",
  "Ricardo",
  "Agustín",
  "Darío",
  "Wilson",
  "Mariano",
  "William",
  "jefferson",
  "Augusto",
  "Facundo",
  "Ezequiel",
  "Giancarlo",
  "Gustavo",
  "Efraín",
  "Jhonathan",
  "John",
  "Edgar",
  "Salvador",
  "Orlando",
  "Abel",
  "Bernardo",
  "Jacinto",
  "Milton",
  "Farid",
  "Octavio",
  "Pastor",
  "Guillermo",
  "Walter",
  "Rolando",
  "Wilmar",
  "Máximo",
  "Marcelo",
  "Gerardo",
  "Waldo",
  "Freddy",
  "Aquiles",
  "Byron",
  "Brayan",
  "Ariel",
  "Arley",
  "Domingo",
  "Segundo",
  "Erasmo",
  "Gilberto",
  "Jesús",
  "Emiliano",
  "Paco",
  "Manolo",
  "Hernán",
  "Jaír",
  "Anderson",
  "Edwin",
  "Ernesto",
  "Paolo",
  "Paulo",
  "Camilo",
  "Osvaldo",
  "Diego Alejandro",
  "Daniel Alejandro",
  "Gabriel Alejandro",
  "Miguel Ángel",
  "Andrés Fernando",
  "León Emilio",
  "Marcos Julián",
  "Juan José",
  "Pedro José",
  "Pedro Juan",
  "Pedro Alexander",
  "Pedro Alejandro",
  "Pedro Pablo",
  "Pedro Antonio",
  "Juan Antonio",
  "José Antonio",
  "Juan Fernando",
  "José Fernando",
  "José Luis",
  "Juan Luis",
  "David Alejandro",
  "Cristian Felipe",
  "Andrés Felipe",
  "José Felipe",
  "Juan Felipe",
  "Juan Esteban",
  "Esteban Andrés",
  "Esteban José",
  "Hugo Pablo",
  "Juan Pablo",
  "José Pablo",
  "Pablo León",
  "Pablo Tomás",
  "Pablo Alejandro",
  "Jorge Pablo",
  "Jorge Esteban",
  "Jorge Andrés",
  "Jorge Armando",
  "Carlos Javier",
  "José Javier",
  "José Manuel",
  "Javier Andrés",
  "Gonzalo Antonio",
  "Eduardo Andrés",
  "Jurge Eduardo",
  "José Eduardo",
  "Néstor Arturo",
  "Néstor Iván",
  "Néstor Edgar",
  "Fabián Ernesto",
  "Johan Andrés",
  "Fabio Leonardo",
  "Fabio Andrés",
  "Jorge Luis",
  "Eduardo Luis",
  "Santiago Luis",
  "Diego Luis",
  "Daniel Andrés",
  "José Daniel",
  "Oscar Andrés",
  "Oscar Leonardo",
  "Héctor Fabio",
  "Héctor Andrés",
  "Victor Andrés",
  "Omar Andrés",
  "Andrés Mauricio",
  "Jose Jaime",
  "Jorge Enrique",
  "Jose Enrique",
  "Manuel Ricardo",
  "Ricardo José",
  "Ricardo Andrés",
  "Jhonathan Andrés",
  "Juan Marcelo",
  "Brayan Andrés",
  "Jesús Andrés",
  "Anderson Jaír",
  "Juan Camilo",
  "José Camilo",
  "Camilo Andrés",
  "Mateo Camilo",
  "Jefferson Arley",
  "Paolo Camilo",
  "Camilo Enrique",
  "Paulo Andrés",
  "Cristian Camilo",
  "Juan Sebastian",
  "Alberto",
  "Luis Alberto",
  "José Alberto",
];
const apellidos = [
  "González",
  "Rodriguez",
  "Gómez",
  "Fernandez",
  "López",
  "Díaz",
  "Martínez",
  "Pérez",
  "García",
  "Sánchez",
  "Romero",
  "Sosa",
  "Álvarez",
  "Torres",
  "Ruiz",
  "Ramírez",
  "Flores",
  "Acosta",
  "Benítez",
  "Medina",
  "Suárez",
  "Herrera",
  "Aguirre",
  "Gutiérrez",
  "Jiménez",
  "Molina",
  "Silva",
  "Castro",
  "Rojas",
  "Ortiz",
  "Núñez",
  "Luna",
  "Cabrera",
  "Ríos",
  "Ferreyra",
  "Godoy",
  "Morales",
  "Domínguez",
  "Moreno",
  "Peralta",
  "Uribe",
  "Vega",
  "Quiroga",
  "Castillo",
  "Muñoz",
  "Ojeda",
  "Ponce",
  "Vera",
  "Váquez",
  "Cardozo",
  "Navarro",
  "Ramos",
  "Arias",
  "Figueroa",
  "Correa",
  "Cáceres",
  "Vargas",
  "Maldonado",
  "Riveros",
  "Méndez",
  "Cruz",
  "Hernández",
  "Paéz",
  "Blanco",
  "Mendoza",
  "Barrios",
  "Escobar",
  "Ávila",
  "Leiva",
  "Acuña",
  "Campos",
  "Duarte",
  "Soto",
  "Bravo",
  "Valdez",
  "Velásquez",
  "Montenegro",
  "Chávez",
  "Arce",
  "Contreras",
  "Sepúlveda",
  "Fuentes",
  "Espinoza",
  "Reyes",
  "Cortés",
  "Vergara",
  "Sandoval",
  "Zuñiga",
  "Orellano",
  "Salazar",
  "Guzmán",
  "Saavedra",
  "Parra",
  "Peña",
  "Salinas",
  "Vidal",
  "Cárdenas",
  "Bustos",
  "Saénz",
  "Carvajal",
  "Alvarado",
  "Bustamante",
  "Toro",
  "Ortega",
  "Venegas",
  "Vanegas",
  "Guerrero",
  "Paredes",
  "Villalobos",
  "Valverde",
  "Mejía",
  "Sabillón",
  "Castellanos",
  "Caballero",
  "Aguilar",
  "Galeano",
  "Báez",
  "Quintana",
  "Ferrari",
  "Bermúdez",
  "Meza",
  "Garrido",
  "Villalba",
  "Ibarra",
  "Gaitán",
  "Cano",
  "Rocha",
  "Iglesias",
  "Quintero",
  "Rivas",
  "Heredia",
  "Chaparro",
  "Delgado",
  "Hurtado",
  "Roca",
  "Valencia",
  "Pineda",
  "Rosas",
  "Valenzuela",
  "Reinoso",
  "Prado",
  "Izquierdo",
  "Cuadrado",
  "Redondo",
  "Arredondo",
  "Pardo",
  "Alfaro",
  "Higuera",
  "Murcia",
  "Garibello",
  "Arteaga",
  "Fajardo",
  "Avellaneda",
  "Prieto",
  "Pinto",
  "Cepeda",
  "Canales",
  "Viera",
  "Quevedo",
  "Perdomo",
  "Bello",
  "Bolaños",
  "Tevez",
  "Estévez",
  "Oviedo",
  "Ulloa",
  "Aguinaga",
  "Jaramillo",
  "Ochoa",
  "Padilla",
  "Palacios",
  "Galvis",
  "Caicedo",
  "Orejuela",
  "Orjuela",
  "Manrique",
  "Penagos",
  "Ceballos",
  "Argüello",
  "Carranza",
  "Villa",
  "Mora",
  "Murillo",
  "Tejada",
  "Montero",
  "Becerra",
  "Gamboa",
  "Guevara",
  "Guerra",
  "Arreol",
  "Mercado",
  "Márquez",
  "Mantilla",
  "Cifuentes",
  "Cervera",
  "Vivas",
  "Chacón",
  "Briceño",
  "Borges",
  "Gil",
  "Enciso",
  "Zambrano",
  "Cardona",
  "Carmona",
  "Rodas",
  "Granados",
  "Ocaña",
  "Solano",
  "Marín",
  "Naranjo",
  "Cervantes",
  "Cuesta",
  "Olivera",
  "Ochoa",
  "Zaragoza",
  "Santodomingo",
  "Rendón",
  "Rondón",
  "Acevedo",
  "Arévalo",
  "Ledesma",
  "Aguirre",
  "Garay",
  "Peñalosa",
  "Rey",
  "Soriano",
  "Galán",
  "Ayala",
  "Duque",
  "Benavides",
  "Serna",
  "Mackenzie",
  "Sabala",
  "Cabañas",
  "Herrada",
  "Gámez",
  "Santos",
  "Arriet",
  "Gil",
  "Bustamante",
  "Falcao",
  "Torrealba",
  "Retamoso",
  "Iguarán",
  "Valentierra",
  "Morón",
  "Pineda",
  "Piñere",
];

// 1) crear una función que me retorne la longitud de un arreglo ingresado como parámetro

// 2) quiero conocer el número de elementos de los arreglos de nombres y apellidos

// 3) quiero saber si en los arreglos está mi nombre y mi apellido

// 4) crear una función para verificar si un nombre existe o un apellido existe dentro del arreglo

// 5) crear una función que inserte un nuevo nombre y otra para que inserte un nuevo apellido

// 6) crear una función para que me inserte el nombre o el apellido después de verificar que no exista

// 7) crear una función que me elija aleatoriamente un nombre y un apellido y me retorne el nombre conformado

// 8) crear una función que me retorne el arreglo de nombres y otra para apellidos ordenado alfabéticamente

// 9) crear una función que me retorne el arreglo de nombres y otra para apellidos ordenado por la cantidad de letras de menor a mayor

// 9) crear una función que me busque una cadena de texto ingresada tanto en los nombres como en los apellidos y me diga cuántos elementos dieron match con esa búsqueda

// 10) crear una función que solo retorne los elementos en nombres y apellidos que tengan por lo menos una 'a'

// 11) crear una función que retorne la suma de la cantidad de letras de todos los nombres y otra para los apellidos

// 12) crear una clase Jugador que tenga propiedades id, nombre, apellido, creadoEn, actualizadoEn

// 13) crear un objeto con el nombre y apellido generado aleatoriamente y siendo creadoEn y actualizadoEn fechas que indican en qué momento el objeto fue creado y actualizado. id debe ser un identificador numérico único

// 14) crear 10 objetos Jugador

// 15) crear una función que me retorne solamente el id y el nombre completo de los jugadores creados
